tap "homebrew/bundle"
tap "homebrew/cask-fonts"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Library for command-line editing
brew "readline"
# Extendable version manager with support for Ruby, Node.js, Erlang & more
brew "asdf"
# C library of Git core methods that is re-entrant and linkable
brew "libgit2"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Cross-platform make
brew "cmake"
# Modern replacement for 'ls'
brew "exa"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Command-line fuzzy finder written in Go
brew "fzf"
# Distributed revision control system
brew "git"
# High-velocity, monorepo-scale workflow for Git
brew "git-branchless"
# Asynchronous event library
brew "libevent"
# Open source suite of directory software
brew "openldap"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Improved top (interactive process viewer)
brew "htop"
# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Command-line JSON pretty-printer
brew "jsonpp"
# Simple terminal UI for git commands
brew "lazygit"
# Pager program similar to more
brew "less"
# C library of Git core methods that is re-entrant and linkable
brew "libgit2@1.5"
# Zstandard is a real-time compression algorithm
brew "zstd"
# C library for reading, creating, and modifying zip archives
brew "libzip"
# Keep your Mac's application settings in sync
brew "mackup"
# Mac App Store command-line interface
brew "mas"
# Simple tool to make locally trusted development certificates
brew "mkcert"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Libraries for security-enabled client and server applications
brew "nss"
# Cryptography and SSL/TLS Toolkit
brew "openssl@1.1"
# Highly capable, feature-rich programming language
brew "perl"
# Manage compile and link flags for libraries
brew "pkg-config"
# Fast, disk space efficient package manager
brew "pnpm"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Tool for downloading RTMP streaming media
brew "rtmpdump"
# Keccak, SHA-3, SHAKE, and RawSHAKE checksum utilities
brew "sha3sum"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Cross-shell prompt for astronauts
brew "starship"
# Manage Git commits as a stack of patches
brew "stgit"
# Simplified and community-driven man pages
brew "tldr"
# Terminal multiplexer
brew "tmux"
# CLI tool that moves files or folder to the trash
brew "trash"
# Vi 'workalike' with many additional features
brew "vim"
# Internet file retriever
brew "wget"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# UNIX shell (command interpreter)
brew "zsh"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# GPU-accelerated terminal emulator
cask "alacritty"
# Application uninstaller
cask "appcleaner"
# Web browser focusing on privacy
cask "brave-browser"
# App to build and share containerized applications and microservices
cask "docker"
# Matrix collaboration client
cask "element"
# Web browser
cask "firefox"
# Clipboard manager for developers
cask "flycut"
# Developer targeted fonts with a high number of glyphs
cask "font-hack-nerd-font"
# Convert your caps lock key or any of your modifier keys to the hyper key
cask "hyperkey"
# Free and open-source RSS reader
cask "netnewswire"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Instant messaging application focusing on security
cask "signal"
# Music streaming service
cask "spotify"
# Native GUI tool for relational databases
cask "tableplus"
# Messaging app with a focus on speed and security
cask "telegram"
# Unpacks archive files
cask "the-unarchiver"
# Open-source code editor
cask "visual-studio-code"
# Multimedia player
cask "vlc"
mas "1Blocker", id: 1365531024
mas "Bitwarden", id: 1352778147
mas "Exporter", id: 1099120373
mas "Goodnotes", id: 1444383602
mas "Keynote", id: 409183694
mas "Noizio", id: 928871589
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Things", id: 904280696
mas "WireGuard", id: 1451685025
vscode "be5invis.toml"
vscode "biomejs.biome"
vscode "bradlc.vscode-tailwindcss"
vscode "dbaeumer.vscode-eslint"
vscode "denoland.vscode-deno"
vscode "eamodio.gitlens"
vscode "EditorConfig.EditorConfig"
vscode "esbenp.prettier-vscode"
vscode "file-icons.file-icons"
vscode "formulahendry.auto-rename-tag"
vscode "golang.go"
vscode "jgclark.vscode-todo-highlight"
vscode "JuanBlanco.solidity"
vscode "mhutchie.git-graph"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.hexeditor"
vscode "rangav.vscode-thunder-client"
vscode "rust-lang.rust-analyzer"
vscode "streetsidesoftware.code-spell-checker"
vscode "svelte.svelte-vscode"
vscode "tombonnike.vscode-status-bar-format-toggle"
vscode "usernamehw.errorlens"
vscode "vadimcn.vscode-lldb"
vscode "VisualStudioExptTeam.intellicode-api-usage-examples"
vscode "VisualStudioExptTeam.vscodeintellicode"
vscode "vscodevim.vim"
vscode "yzhang.markdown-all-in-one"
vscode "zhuangtongfa.material-theme"
vscode "ziglang.vscode-zig"
