tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"
# Open-source code editor
cask "visual-studio-code"
