# TODO: Ensure that this is always up-to-date.
# Note that we need to keep this as `brew --prefix` can't be used until Homebrew was
#   added to our path below.
# Homebrew makes a distiction between Apple Silicon and Intel.
#   See: https://stackoverflow.com/a/71186857 and https://stackoverflow.com/a/65259353
HOMEBREW_ROOT_PATH="/usr/local"
if [ $(uname -p) = 'arm' ]; then
  HOMEBREW_ROOT_PATH="/opt/homebrew"
fi

# Path
typeset -U path
path=(
  "/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
  "$HOMEBREW_ROOT_PATH/bin"
  $path
)

# Exports
export NULLCMD=bat
export EDITOR='nvim';
export LANG='en_US.UTF-8';
export LC_ALL='en_US.UTF-8';
export PUBKEY_FILE_NAME='id_ed25519.pub'
export DOTFILES="$HOME/.dotfiles"
export PUBKEY_FILE_PATH="$HOME/.ssh/$PUBKEY_FILE_NAME"
export HOMEBREW_PREFIX=$(brew --prefix)
export HOMEBREW_CASK_OPTS="--no-quarantine --no-binaries"

# Functions
function exists() {
  # See: https://stackoverflow.com/a/677212/1341838
  command -v $1 >/dev/null 2>&1
}

function suppress_error() {
  "$@" || true
}

# asdf
. "$HOMEBREW_PREFIX/opt/asdf/libexec/asdf.sh"
eval "$(asdf exec direnv hook zsh)"
direnv() { asdf exec direnv "$@"; }
