# Exports
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# Functions
precmd() {
  source "$DOTFILES/zsh/aliases.zsh"
}

# Starship
eval "$(starship init zsh)"

# zoxide
eval "$(zoxide init zsh)"

# Z shell Plugins
source "$(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
source "$(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
